VIA_ENABLE = no
COMBO_ENABLE = yes
COMMAND_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RAW_ENABLE = no
CONSOLE_ENABLE = yes
DEBOUNCE_TYPE = asym_eager_defer_pk
MOUSEKEY_ENABLE = no
BOOTMAGIC_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = AW20216

SRC += encoder.c